export type Task = {
  id: string;
  title: string;
  status: "pending" | "in-progress" | "completed";
  priority?: "low" | "medium" | "high";
  dueDate: string;
};

export type Collaborator = {
  id: string;
  name: string;
  role?: string;
  avatar?: string;
};

export type Activity = {
  id: string;
  message: string;
  timestamp: string;
  type: "payment" | "invite" | "note" | "other";
  title: string;
  description?: string;
  time: string;
  icon?: string;
};

export type Event = {
  id: string;
  title: string;
  venue: string;
  startDate: string;
  endDate?: string;
  image: string;
  eventManager?: string;
  eventId?: string;
  budget?: number;
  expenditure?: { current: number; completed: number };
  collaborators: Collaborator[];
  tasks: Task[];
  activities: Activity[];
};

export const demoEvents: Event[] = [
  {
    id: "1",
    title: "Tech Innovators Conference 2025",
    venue: "Eko Hotels",
    startDate: "2025-10-10",
    endDate: "2025-10-12",
    image: "/images/tech-conference.jpg",
    eventManager: "John Doe",
    eventId: "TIC2025",
    budget: 500000,
    expenditure: { current: 250000, completed: 75 },
    collaborators: [
      { id: "u1", name: "John Doe", role: "Organizer" },
      { id: "u2", name: "Sarah Johnson", role: "Marketing Lead" },
      { id: "u3", name: "Michael Lee", role: "Tech Support" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Book venue at Eko Hotels",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-20",
      },
      {
        id: "t2",
        title: "Confirm keynote speakers",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-09-25",
      },
      {
        id: "t3",
        title: "Design event website",
        status: "completed",
        priority: "medium",
        dueDate: "2025-09-15",
      },
      {
        id: "t4",
        title: "Secure sponsors (MTN, Flutterwave)",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-09-28",
      },
      {
        id: "t5",
        title: "Print event banners and branding",
        status: "pending",
        priority: "low",
        dueDate: "2025-10-05",
      },
      {
        id: "t6",
        title: "Organize volunteer training",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-03",
      },
      {
        id: "t7",
        title: "Set up registration portal",
        status: "completed",
        priority: "medium",
        dueDate: "2025-09-10",
      },
      {
        id: "t8",
        title: "Arrange accommodation for VIPs",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-10-01",
      },
      {
        id: "t9",
        title: "Test live-stream equipment",
        status: "pending",
        priority: "high",
        dueDate: "2025-10-08",
      },
      {
        id: "t10",
        title: "Finalize event agenda",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-09-30",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "John Doe added a new task: Book venue at Eko Hotels",
        timestamp: "2025-09-12T10:30:00Z",
        type: "note",
        title: "Task Added",
        description: "New task created for venue booking",
        time: "10:30 AM",
      },
      {
        id: "a2",
        message: "Venue booking confirmed with deposit paid",
        timestamp: "2025-09-15T14:00:00Z",
        type: "payment",
        title: "Payment Made",
        description: "Deposit paid for venue booking",
        time: "2:00 PM",
      },
      {
        id: "a3",
        message: "Sarah Johnson updated task: Confirm keynote speakers",
        timestamp: "2025-09-18T09:15:00Z",
        type: "note",
        title: "Task Updated",
        description: "Keynote speakers task progress updated",
        time: "9:15 AM",
      },
      {
        id: "a4",
        message: "Registration portal went live",
        timestamp: "2025-09-20T16:45:00Z",
        type: "note",
        title: "Portal Live",
        description: "Registration portal successfully launched",
        time: "4:45 PM",
      },
      {
        id: "a5",
        message: "Sponsorship meeting held with Flutterwave",
        timestamp: "2025-09-22T12:10:00Z",
        type: "note",
        title: "Meeting Held",
        description: "Sponsorship discussion with Flutterwave",
        time: "12:10 PM",
      },
    ],
  },
  {
    id: "2",
    title: "Wedding of Tolu & Ada",
    venue: "Abuja Wedding Hall",
    startDate: "2025-12-15",
    image: "/images/wedding.jpg",
    eventManager: "Chinedu Okafor",
    budget: 200000,
    expenditure: { current: 80000, completed: 40 },
    collaborators: [
      { id: "u4", name: "Tolu Adebayo", role: "Groom" },
      { id: "u5", name: "Ada Nwachukwu", role: "Bride" },
      { id: "u6", name: "Chinedu Okafor", role: "Planner" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Book wedding hall",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-10",
      },
      {
        id: "t2",
        title: "Hire photographer and videographer",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-01",
      },
      {
        id: "t3",
        title: "Send wedding invitations",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-01",
      },
      {
        id: "t4",
        title: "Order wedding cake",
        status: "pending",
        priority: "low",
        dueDate: "2025-11-15",
      },
      {
        id: "t5",
        title: "Book honeymoon trip",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-20",
      },
      {
        id: "t6",
        title: "Hire live band",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-10",
      },
      {
        id: "t7",
        title: "Arrange bridesmaids' dresses",
        status: "completed",
        priority: "medium",
        dueDate: "2025-09-25",
      },
      {
        id: "t8",
        title: "Confirm catering services",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-15",
      },
      {
        id: "t9",
        title: "Book makeup artist",
        status: "completed",
        priority: "medium",
        dueDate: "2025-09-18",
      },
      {
        id: "t10",
        title: "Plan traditional attire",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-11-05",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "Ada confirmed booking for the wedding hall",
        timestamp: "2025-09-10T11:30:00Z",
        type: "note",
        title: "Venue Booked",
        description: "Wedding hall booking confirmed",
        time: "11:30 AM",
      },
      {
        id: "a2",
        message: "Tolu met with the photographer for contract signing",
        timestamp: "2025-09-20T13:45:00Z",
        type: "note",
        title: "Contract Signed",
        description: "Photographer contract finalized",
        time: "1:45 PM",
      },
      {
        id: "a3",
        message: "Bridesmaids' dresses delivered to the tailor",
        timestamp: "2025-09-25T15:00:00Z",
        type: "note",
        title: "Dresses Delivered",
        description: "Bridesmaids dresses for tailoring",
        time: "3:00 PM",
      },
      {
        id: "a4",
        message: "Makeup artist confirmed for December 15",
        timestamp: "2025-09-28T08:20:00Z",
        type: "note",
        title: "Makeup Artist Confirmed",
        description: "Makeup services booked",
        time: "8:20 AM",
      },
      {
        id: "a5",
        message: "Meeting scheduled with catering team",
        timestamp: "2025-09-30T17:10:00Z",
        type: "note",
        title: "Catering Meeting",
        description: "Scheduled meeting with caterers",
        time: "5:10 PM",
      },
    ],
  },
  {
    id: "3",
    title: "Startup Pitch Day",
    venue: "Co-Creation Hub",
    startDate: "2025-11-05",
    image: "/images/pitch-day.jpg",
    eventManager: "Emeka Ibe",
    eventId: "SPD2025",
    budget: 150000,
    expenditure: { current: 60000, completed: 40 },
    collaborators: [
      { id: "u7", name: "Emeka Ibe", role: "Event Lead" },
      { id: "u8", name: "Funke Adeyemi", role: "Investor Relations" },
      { id: "u9", name: "Daniel Ojo", role: "Media & Comms" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Confirm venue at Co-Creation Hub",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-12",
      },
      {
        id: "t2",
        title: "Invite top investors",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-01",
      },
      {
        id: "t3",
        title: "Shortlist startup applicants",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-09-25",
      },
      {
        id: "t4",
        title: "Design promotional flyers",
        status: "completed",
        priority: "medium",
        dueDate: "2025-09-18",
      },
      {
        id: "t5",
        title: "Schedule media coverage",
        status: "pending",
        priority: "low",
        dueDate: "2025-10-10",
      },
      {
        id: "t6",
        title: "Confirm judges panel",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-09-30",
      },
      {
        id: "t7",
        title: "Arrange catering for guests",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-20",
      },
      {
        id: "t8",
        title: "Prepare pitch evaluation forms",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-15",
      },
      {
        id: "t9",
        title: "Test projector and sound system",
        status: "pending",
        priority: "high",
        dueDate: "2025-11-02",
      },
      {
        id: "t10",
        title: "Draft follow-up emails to investors",
        status: "pending",
        priority: "low",
        dueDate: "2025-11-07",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "Venue confirmed at CcHub rooftop hall",
        timestamp: "2025-09-12T09:00:00Z",
        type: "note",
        title: "Venue Confirmed",
        description: "Co-Creation Hub venue booked",
        time: "9:00 AM",
      },
      {
        id: "a2",
        message: "Design team shared promotional flyers",
        timestamp: "2025-09-18T15:30:00Z",
        type: "note",
        title: "Flyers Ready",
        description: "Promotional materials prepared",
        time: "3:30 PM",
      },
      {
        id: "a3",
        message: "30 startups applied for the pitch event",
        timestamp: "2025-09-20T17:45:00Z",
        type: "note",
        title: "Applications Received",
        description: "Startup applications submitted",
        time: "5:45 PM",
      },
      {
        id: "a4",
        message: "Investors outreach email campaign launched",
        timestamp: "2025-09-23T11:10:00Z",
        type: "invite",
        title: "Investors Invited",
        description: "Email campaign started",
        time: "11:10 AM",
      },
      {
        id: "a5",
        message: "Judges panel shortlist prepared",
        timestamp: "2025-09-28T13:50:00Z",
        type: "note",
        title: "Judges Shortlisted",
        description: "Potential judges identified",
        time: "1:50 PM",
      },
    ],
  },
  {
    id: "4",
    title: "Charity Gala Night",
    venue: "Civic Centre",
    startDate: "2025-11-20",
    image: "/images/charity-gala.jpg",
    eventManager: "Ngozi Okeke",
    budget: 300000,
    expenditure: { current: 120000, completed: 40 },
    collaborators: [
      { id: "u10", name: "Ngozi Okeke", role: "Event Director" },
      { id: "u11", name: "Bayo Alade", role: "Fundraising Lead" },
      { id: "u12", name: "Aisha Sule", role: "PR Manager" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Secure ballroom at Civic Centre",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-15",
      },
      {
        id: "t2",
        title: "Hire live orchestra",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-05",
      },
      {
        id: "t3",
        title: "Design and print invitations",
        status: "completed",
        priority: "medium",
        dueDate: "2025-09-25",
      },
      {
        id: "t4",
        title: "Confirm celebrity host",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-01",
      },
      {
        id: "t5",
        title: "Secure catering contract",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-10-10",
      },
      {
        id: "t6",
        title: "Organize silent auction items",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-05",
      },
      {
        id: "t7",
        title: "Book media coverage",
        status: "in-progress",
        priority: "low",
        dueDate: "2025-10-15",
      },
      {
        id: "t8",
        title: "Plan table seating arrangements",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-10",
      },
      {
        id: "t9",
        title: "Print event program",
        status: "pending",
        priority: "low",
        dueDate: "2025-11-15",
      },
      {
        id: "t10",
        title: "Finalize donation platform",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-30",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "Civic Centre booked for Nov 20",
        timestamp: "2025-09-15T10:20:00Z",
        type: "note",
        title: "Venue Booked",
        description: "Civic Centre ballroom secured",
        time: "10:20 AM",
      },
      {
        id: "a2",
        message: "Design team delivered event invitations",
        timestamp: "2025-09-25T16:40:00Z",
        type: "note",
        title: "Invitations Ready",
        description: "Gala invitations printed",
        time: "4:40 PM",
      },
      {
        id: "a3",
        message: "Negotiations ongoing with celebrity host",
        timestamp: "2025-09-28T12:00:00Z",
        type: "note",
        title: "Host Negotiations",
        description: "Discussions with potential host",
        time: "12:00 PM",
      },
      {
        id: "a4",
        message: "Donation platform tested successfully",
        timestamp: "2025-09-30T09:45:00Z",
        type: "note",
        title: "Platform Tested",
        description: "Donation system working",
        time: "9:45 AM",
      },
      {
        id: "a5",
        message: "Auction committee met to discuss items",
        timestamp: "2025-10-02T14:30:00Z",
        type: "note",
        title: "Auction Meeting",
        description: "Silent auction planning",
        time: "2:30 PM",
      },
    ],
  },
  {
    id: "5",
    title: "Music Festival: AfroVibes 2025",
    venue: "Independence Square",
    startDate: "2025-12-05",
    endDate: "2025-12-06",
    image: "/images/music-festival.jpg",
    eventManager: "Kwame Mensah",
    eventId: "AFV2025",
    budget: 800000,
    expenditure: { current: 320000, completed: 40 },
    collaborators: [
      { id: "u13", name: "Kwame Mensah", role: "Festival Director" },
      { id: "u14", name: "Lola Balogun", role: "Artist Relations" },
      { id: "u15", name: "James Smith", role: "Logistics Coordinator" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Secure venue (Independence Square)",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-18",
      },
      {
        id: "t2",
        title: "Line up international headliners",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-10",
      },
      {
        id: "t3",
        title: "Design festival stage setup",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-10-15",
      },
      {
        id: "t4",
        title: "Set up ticketing platform",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-25",
      },
      {
        id: "t5",
        title: "Apply for city permits",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-05",
      },
      {
        id: "t6",
        title: "Arrange food and drinks vendors",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-01",
      },
      {
        id: "t7",
        title: "Hire security company",
        status: "pending",
        priority: "high",
        dueDate: "2025-10-20",
      },
      {
        id: "t8",
        title: "Organize artist accommodations",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-11-10",
      },
      {
        id: "t9",
        title: "Book backup generators",
        status: "completed",
        priority: "medium",
        dueDate: "2025-09-28",
      },
      {
        id: "t10",
        title: "Launch marketing campaign",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-01",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "Independence Square secured for festival",
        timestamp: "2025-09-18T10:15:00Z",
        type: "note",
        title: "Venue Secured",
        description: "Main venue confirmed",
        time: "10:15 AM",
      },
      {
        id: "a2",
        message: "Ticketing platform launched online",
        timestamp: "2025-09-25T08:45:00Z",
        type: "note",
        title: "Tickets Live",
        description: "Ticket sales started",
        time: "8:45 AM",
      },
      {
        id: "a3",
        message: "Marketing team released teaser videos",
        timestamp: "2025-09-27T11:20:00Z",
        type: "note",
        title: "Marketing Launch",
        description: "Teaser campaign started",
        time: "11:20 AM",
      },
      {
        id: "a4",
        message: "Stage design draft shared with production",
        timestamp: "2025-09-29T17:00:00Z",
        type: "note",
        title: "Stage Design",
        description: "Stage layout shared",
        time: "5:00 PM",
      },
      {
        id: "a5",
        message: "Meeting with Accra City officials on permits",
        timestamp: "2025-10-01T09:30:00Z",
        type: "note",
        title: "Permit Meeting",
        description: "City permit discussions",
        time: "9:30 AM",
      },
    ],
  },
  {
    id: "6",
    title: "Corporate Annual General Meeting",
    venue: "Grand Hyatt Dubai",
    startDate: "2025-10-25",
    image: "/images/agm.jpg",
    eventManager: "Ahmed Khan",
    eventId: "AGM2025",
    budget: 250000,
    expenditure: { current: 100000, completed: 40 },
    collaborators: [
      { id: "u16", name: "Ahmed Khan", role: "Event Manager" },
      { id: "u17", name: "Sophia Chen", role: "Finance Lead" },
      { id: "u18", name: "David Miller", role: "Communications Officer" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Book 5-star hotel conference hall",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-20",
      },
      {
        id: "t2",
        title: "Prepare financial presentation slides",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-10",
      },
      {
        id: "t3",
        title: "Confirm travel for board members",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-10-05",
      },
      {
        id: "t4",
        title: "Distribute AGM invitations to shareholders",
        status: "completed",
        priority: "medium",
        dueDate: "2025-09-28",
      },
      {
        id: "t5",
        title: "Prepare press release draft",
        status: "pending",
        priority: "low",
        dueDate: "2025-10-15",
      },
      {
        id: "t6",
        title: "Arrange catering and beverages",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-20",
      },
      {
        id: "t7",
        title: "Confirm IT support for live-stream",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-12",
      },
      {
        id: "t8",
        title: "Print shareholder reports",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-18",
      },
      {
        id: "t9",
        title: "Book translators for international attendees",
        status: "pending",
        priority: "low",
        dueDate: "2025-10-16",
      },
      {
        id: "t10",
        title: "Rehearse board presentations",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-22",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "Hotel ballroom booked at Grand Hyatt Dubai",
        timestamp: "2025-09-20T14:40:00Z",
        type: "note",
        title: "Venue Booked",
        description: "Conference hall secured",
        time: "2:40 PM",
      },
      {
        id: "a2",
        message: "Invitations sent to shareholders",
        timestamp: "2025-09-28T09:00:00Z",
        type: "invite",
        title: "Invitations Sent",
        description: "Shareholders notified",
        time: "9:00 AM",
      },
      {
        id: "a3",
        message: "Finance team shared draft of Q3 results",
        timestamp: "2025-09-30T16:10:00Z",
        type: "note",
        title: "Financial Draft",
        description: "Q3 results prepared",
        time: "4:10 PM",
      },
      {
        id: "a4",
        message: "Board travel bookings initiated",
        timestamp: "2025-10-01T11:25:00Z",
        type: "note",
        title: "Travel Arranged",
        description: "Board member travel",
        time: "11:25 AM",
      },
      {
        id: "a5",
        message: "Meeting with IT team on live-stream setup",
        timestamp: "2025-10-03T13:50:00Z",
        type: "note",
        title: "IT Meeting",
        description: "Live-stream planning",
        time: "1:50 PM",
      },
    ],
  },
  {
    id: "7",
    title: "Startup Pitch Day",
    venue: "Zone Tech Park",
    startDate: "2025-11-05",
    image: "/images/startup-pitch.jpg",
    eventManager: "Chinedu Okafor",
    eventId: "ZPD2025",
    budget: 120000,
    expenditure: { current: 48000, completed: 40 },
    collaborators: [
      { id: "u19", name: "Chinedu Okafor", role: "Program Lead" },
      { id: "u20", name: "Ifeoma Umeh", role: "Logistics Coordinator" },
      { id: "u21", name: "Peter Adeyemi", role: "Media Manager" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Confirm investor guest list",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-25",
      },
      {
        id: "t2",
        title: "Book auditorium",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-15",
      },
      {
        id: "t3",
        title: "Shortlist startups",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-05",
      },
      {
        id: "t4",
        title: "Prepare stage design",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-15",
      },
      {
        id: "t5",
        title: "Arrange media partnerships",
        status: "in-progress",
        priority: "low",
        dueDate: "2025-10-10",
      },
      {
        id: "t6",
        title: "Design event brochure",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-20",
      },
      {
        id: "t7",
        title: "Book catering",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-25",
      },
      {
        id: "t8",
        title: "Confirm judges panel",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-12",
      },
      {
        id: "t9",
        title: "Run rehearsal with startups",
        status: "pending",
        priority: "high",
        dueDate: "2025-11-02",
      },
      {
        id: "t10",
        title: "Prepare investor packs",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-01",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "Zone Tech Park booked for Nov 5",
        timestamp: "2025-09-15T12:20:00Z",
        type: "note",
        title: "Venue Booked",
        description: "Auditorium secured",
        time: "12:20 PM",
      },
      {
        id: "a2",
        message: "15 startups applied for selection",
        timestamp: "2025-09-20T10:40:00Z",
        type: "note",
        title: "Applications Received",
        description: "Startup submissions",
        time: "10:40 AM",
      },
      {
        id: "a3",
        message: "Investor invites sent",
        timestamp: "2025-09-25T16:30:00Z",
        type: "invite",
        title: "Investors Invited",
        description: "Investor notifications sent",
        time: "4:30 PM",
      },
      {
        id: "a4",
        message: "Preliminary shortlist of startups shared",
        timestamp: "2025-10-02T09:15:00Z",
        type: "note",
        title: "Startups Shortlisted",
        description: "Initial selection made",
        time: "9:15 AM",
      },
      {
        id: "a5",
        message: "Judges panel preliminary confirmed",
        timestamp: "2025-10-04T15:45:00Z",
        type: "note",
        title: "Judges Confirmed",
        description: "Panel members agreed",
        time: "3:45 PM",
      },
    ],
  },
  {
    id: "8",
    title: "Music Concert: Lagos Live",
    venue: "TBS Arena",
    startDate: "2025-12-12",
    image: "/images/concert.jpg",
    eventManager: "DJ Yemi",
    eventId: "LL2025",
    budget: 600000,
    expenditure: { current: 240000, completed: 40 },
    collaborators: [
      { id: "u22", name: "DJ Yemi", role: "Music Director" },
      { id: "u23", name: "Fatima Hassan", role: "Operations Lead" },
      { id: "u24", name: "Kunle Fashola", role: "Stage Manager" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Confirm headline acts",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-20",
      },
      {
        id: "t2",
        title: "Book stage setup & lighting",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-05",
      },
      {
        id: "t3",
        title: "Organize ticket sales online",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-28",
      },
      {
        id: "t4",
        title: "Set up backstage logistics",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-15",
      },
      {
        id: "t5",
        title: "Hire 50 security staff",
        status: "pending",
        priority: "high",
        dueDate: "2025-11-10",
      },
      {
        id: "t6",
        title: "Arrange food stalls",
        status: "pending",
        priority: "low",
        dueDate: "2025-11-20",
      },
      {
        id: "t7",
        title: "Book ambulance service",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-22",
      },
      {
        id: "t8",
        title: "Rehearsals with main acts",
        status: "pending",
        priority: "medium",
        dueDate: "2025-12-05",
      },
      {
        id: "t9",
        title: "Finalize media partnerships",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-10-20",
      },
      {
        id: "t10",
        title: "Print VIP passes",
        status: "pending",
        priority: "low",
        dueDate: "2025-12-01",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "Wizkid confirmed as headline act",
        timestamp: "2025-09-20T18:00:00Z",
        type: "note",
        title: "Headliner Confirmed",
        description: "Main artist booked",
        time: "6:00 PM",
      },
      {
        id: "a2",
        message: "Ticketing platform launched",
        timestamp: "2025-09-28T11:30:00Z",
        type: "note",
        title: "Tickets Live",
        description: "Sales platform active",
        time: "11:30 AM",
      },
      {
        id: "a3",
        message: "Lighting supplier shared first draft plan",
        timestamp: "2025-10-01T09:00:00Z",
        type: "note",
        title: "Lighting Plan",
        description: "Stage lighting design",
        time: "9:00 AM",
      },
      {
        id: "a4",
        message: "Meeting with Lagos state officials",
        timestamp: "2025-10-03T15:10:00Z",
        type: "note",
        title: "Government Meeting",
        description: "Permit discussions",
        time: "3:10 PM",
      },
      {
        id: "a5",
        message: "Security agency preliminary discussions",
        timestamp: "2025-10-07T13:40:00Z",
        type: "note",
        title: "Security Planning",
        description: "Security arrangements",
        time: "1:40 PM",
      },
    ],
  },
  {
    id: "9",
    title: "Fashion Week: Africa Style",
    venue: "Civic Center",
    startDate: "2025-12-01",
    endDate: "2025-12-05",
    image: "/images/fashion-week.jpg",
    eventManager: "Ifunanya Okoro",
    eventId: "FW2025",
    budget: 400000,
    expenditure: { current: 160000, completed: 40 },
    collaborators: [
      { id: "u25", name: "Ifunanya Okoro", role: "Creative Director" },
      { id: "u26", name: "Oluwaseun Bello", role: "PR Lead" },
      { id: "u27", name: "Grace Williams", role: "Model Coordinator" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Secure Civic Center halls",
        status: "completed",
        priority: "high",
        dueDate: "2025-09-18",
      },
      {
        id: "t2",
        title: "Confirm designers lineup",
        status: "in-progress",
        priority: "high",
        dueDate: "2025-10-05",
      },
      {
        id: "t3",
        title: "Book runway models",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-10-12",
      },
      {
        id: "t4",
        title: "Design event posters",
        status: "completed",
        priority: "low",
        dueDate: "2025-09-25",
      },
      {
        id: "t5",
        title: "Set up media accreditation process",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-15",
      },
      {
        id: "t6",
        title: "Book makeup and styling team",
        status: "pending",
        priority: "medium",
        dueDate: "2025-10-20",
      },
      {
        id: "t7",
        title: "Confirm after-party venue",
        status: "pending",
        priority: "low",
        dueDate: "2025-11-01",
      },
      {
        id: "t8",
        title: "Organize sponsor booths",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-11-10",
      },
      {
        id: "t9",
        title: "Schedule rehearsals",
        status: "pending",
        priority: "medium",
        dueDate: "2025-11-15",
      },
      {
        id: "t10",
        title: "Print backstage passes",
        status: "pending",
        priority: "low",
        dueDate: "2025-11-20",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "20 designers confirmed participation",
        timestamp: "2025-09-18T12:10:00Z",
        type: "note",
        title: "Designers Confirmed",
        description: "Participating designers",
        time: "12:10 PM",
      },
      {
        id: "a2",
        message: "Event posters printed and distributed",
        timestamp: "2025-09-25T14:30:00Z",
        type: "note",
        title: "Posters Distributed",
        description: "Marketing materials ready",
        time: "2:30 PM",
      },
      {
        id: "a3",
        message: "Discussions ongoing with global buyers",
        timestamp: "2025-09-28T16:20:00Z",
        type: "note",
        title: "Buyer Discussions",
        description: "International buyer outreach",
        time: "4:20 PM",
      },
      {
        id: "a4",
        message: "Sponsor booths draft layout shared",
        timestamp: "2025-10-01T11:15:00Z",
        type: "note",
        title: "Sponsor Layout",
        description: "Booth arrangement plan",
        time: "11:15 AM",
      },
      {
        id: "a5",
        message: "First batch of models auditioned",
        timestamp: "2025-10-03T09:45:00Z",
        type: "note",
        title: "Model Auditions",
        description: "Model selection process",
        time: "9:45 AM",
      },
    ],
  },
  {
    id: "10",
    title: "Graduation Party",
    venue: "University Hall, UNILAG",
    startDate: "2025-07-12",
    image: "/images/graduation.jpg",
    eventManager: "UNILAG Crew",
    budget: 50000,
    expenditure: { current: 20000, completed: 40 },
    collaborators: [
      { id: "u28", name: "UNILAG Crew", role: "Organizers" },
      { id: "u29", name: "Chika Eze", role: "Cultural Coordinator" },
      { id: "u30", name: "Michael Johnson", role: "Security Lead" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Book University Hall",
        status: "completed",
        priority: "high",
        dueDate: "2025-06-15",
      },
      {
        id: "t2",
        title: "Confirm DJ",
        status: "completed",
        priority: "medium",
        dueDate: "2025-06-20",
      },
      {
        id: "t3",
        title: "Arrange catering service",
        status: "in-progress",
        priority: "medium",
        dueDate: "2025-06-25",
      },
      {
        id: "t4",
        title: "Design party flyers",
        status: "completed",
        priority: "low",
        dueDate: "2025-06-22",
      },
      {
        id: "t5",
        title: "Book security team",
        status: "pending",
        priority: "medium",
        dueDate: "2025-07-01",
      },
      {
        id: "t6",
        title: "Hire photographer",
        status: "pending",
        priority: "low",
        dueDate: "2025-07-05",
      },
      {
        id: "t7",
        title: "Set up ticket sales booth",
        status: "completed",
        priority: "medium",
        dueDate: "2025-06-28",
      },
      {
        id: "t8",
        title: "Confirm decoration vendor",
        status: "pending",
        priority: "medium",
        dueDate: "2025-07-02",
      },
      {
        id: "t9",
        title: "Organize class performance",
        status: "in-progress",
        priority: "low",
        dueDate: "2025-07-08",
      },
      {
        id: "t10",
        title: "Finalize guest list",
        status: "pending",
        priority: "high",
        dueDate: "2025-07-10",
      },
    ],
    activities: [
      {
        id: "a1",
        message: "DJ confirmed for graduation party",
        timestamp: "2025-06-20T10:15:00Z",
        type: "note",
        title: "DJ Booked",
        description: "Entertainment confirmed",
        time: "10:15 AM",
      },
      {
        id: "a2",
        message: "Flyers printed and distributed on campus",
        timestamp: "2025-06-22T15:00:00Z",
        type: "note",
        title: "Flyers Distributed",
        description: "Marketing materials ready",
        time: "3:00 PM",
      },
      {
        id: "a3",
        message: "Catering service negotiations ongoing",
        timestamp: "2025-06-25T11:20:00Z",
        type: "note",
        title: "Catering Negotiations",
        description: "Food service discussions",
        time: "11:20 AM",
      },
      {
        id: "a4",
        message: "Ticket sales booth opened at SU office",
        timestamp: "2025-06-28T09:40:00Z",
        type: "note",
        title: "Ticket Booth Open",
        description: "Sales started",
        time: "9:40 AM",
      },
      {
        id: "a5",
        message: "Student decoration team contacted",
        timestamp: "2025-07-01T14:25:00Z",
        type: "note",
        title: "Decoration Team",
        description: "Decorations planning",
        time: "2:25 PM",
      },
    ],
  },
];
